version: '3.8'

services:
  mysql:
    container_name: 'api_mysql_development'
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .local/data/mysql:/var/lib/mysql:rw
      - .local/init/mysql:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_dev
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    cap_add: [ SYS_NICE ]
